/**
* DB/Items/ItemTable.js
*
* This file is part of ROBrowser, Ragnarok Online in the Web Browser (http://www.robrowser.com/).
*
* @author Vincent Thibault
* (auto-generated)
*/

define(function()
{
	"use strict";


	return {
			"1": {
			"identifiedDisplayName": "Iron Lamellar",
			"identifiedResourceName": "\xbe\xc6\xb8\xd3",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
			],
			"BaseHP": 74,
			"BaseDEF": 50,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 0
		},
			"2": {
			"identifiedDisplayName": "Steel Chainmail",
			"identifiedResourceName": "\xb8\xde\xc0\xcf",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
			],
			"BaseHP": 80,
			"BaseDEF": 54,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
			"3": {
			"identifiedDisplayName": "Tempered Platemail",
			"identifiedResourceName": "\xc7\xc3\xb7\xb9\xc0\xcc\xc6\xae",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
			],
			"BaseHP": 86,
			"BaseDEF": 58,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 0
		},
			"4": {
			"identifiedDisplayName": "Ironweave Coat",
			"identifiedResourceName": "\xb8\xc7\xc6\xb2",
			"identifiedDescriptionName": [
				"Mage Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
			],
			"BaseHP": 40,
			"BaseMP": 6,
			"BaseDEF": 32,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 0
		},
			"5": {
			"identifiedDisplayName": "Runic Doublet",
			"identifiedResourceName": "\xc3\xb5\xbb\xe7\xc0\xc7\xb0\xa1\xc8\xa3",
			"identifiedDescriptionName": [
				"Mage Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
			],
			"BaseHP": 44,
			"BaseMP": 7,
			"BaseDEF": 35,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
			"6": {
			"identifiedDisplayName": "Battlemage Regalia",
			"identifiedResourceName": "\xbf\xc0\xb5\xf2\xc0\xc7\xc3\xe0\xba\xb9",
			"identifiedDescriptionName": [
				"Mage Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
			],
			"BaseHP": 48,
			"BaseMP": 8,
			"BaseDEF": 38,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 0
		},
			"7": {
			"identifiedDisplayName": "Apprentice Robe",
			"identifiedResourceName": "\xb7\xd5\xc4\xda\xc6\xae",
			"identifiedDescriptionName": [
				"Light Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$mdef$ MDEF",
			],
			"BaseHP": 26,
			"BaseMP": 17,
			"BaseDEF": 11,
			"BaseMDEF": 40,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 0
		},
			"8": {
			"identifiedDisplayName": "Spellweave Gown",
			"identifiedResourceName": "\xc0\xce\xc5\xa9\xb7\xb9\xb5\xf0\xba\xed\xbf\xdc\xc5\xf5",
			"identifiedDescriptionName": [
				"Light Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$mdef$ MDEF",
			],
			"BaseHP": 28,
			"BaseMP": 20,
			"BaseDEF": 13,
			"BaseMDEF": 48,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
			"9": {
			"identifiedDisplayName": "Arcane Raiment",
			"identifiedResourceName": "\xc5\xa9\xb8\xb2\xc1\xf0\xb7\xce\xba\xea",
			"identifiedDescriptionName": [
				"Light Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$mdef$ MDEF",
			],
			"BaseHP": 30,
			"BaseMP": 23,
			"BaseDEF": 15,
			"BaseMDEF": 56,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 0
		},
			"10": {
			"identifiedDisplayName": "Iron Buckler",
			"identifiedResourceName": "\xb9\xf6\xc5\xac\xb7\xaf",
			"identifiedDescriptionName": [
				"Shield $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def2$% to Physical Block",
				"+$mdef2$% to Magical Block"
			],
			"BaseHP": 22,
			"BaseDEF2": 100,
			"BaseMDEF2": 50,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
			"11": {
			"identifiedDisplayName": "Kite Shield",
			"identifiedResourceName": "\xbd\xaf\xb5\xe5",
			"identifiedDescriptionName": [
				"Shield $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def2$% to Physical Block",
				"+$mdef2$% to Magical Block"
			],
			"BaseHP": 25,
			"BaseDEF2": 120,
			"BaseMDEF2": 60,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
			"12": {
			"identifiedDisplayName": "Angelic Shield",
			"identifiedResourceName": "\xc7\xc3\xb7\xa1\xc6\xbc\xb3\xd1\xbd\xaf\xb5\xe5",
			"identifiedDescriptionName": [
				"Shield $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def2$% to Physical Block",
				"+$mdef2$% to Magical Block"
			],
			"BaseHP": 28,
			"BaseDEF2": 140,
			"BaseMDEF2": 70,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"13": {
			"identifiedDisplayName": "Cantrip Spellbook",
			"identifiedResourceName": "\xba\xcf",
			"identifiedDescriptionName": [
				"Off-Hand $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mdef$ MDEF",
				"+$mdef2$% to Magical Block",
				"+$skilldmg$% Skill Damage"
			],
			"BaseMDEF": 24,
			"BaseMDEF2": 150,
			"BaseSKILLDMG": 12,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
			"14": {
			"identifiedDisplayName": "Ancient Spellbook",
			"identifiedResourceName": "\xc7\xf6\xc0\xda\xc0\xc7\xc0\xcf\xb1\xe2",
			"identifiedDescriptionName": [
				"Off-Hand $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mdef$ MDEF",
				"+$mdef2$% to Magical Block",
				"+$skilldmg$% Skill Damage"
			],
			"BaseMDEF": 27,
			"BaseMDEF2": 170,
			"BaseSKILLDMG": 13,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
			"15": {
			"identifiedDisplayName": "Magus Spellbook",
			"identifiedResourceName": "\xb8\xde\xb8\xf0\xb6\xf3\xc0\xcc\xc1\xee\xba\xcf",
			"identifiedDescriptionName": [
				"Off-Hand $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mdef$ MDEF",
				"+$mdef2$% to Magical Block",
				"+$skilldmg$% Skill Damage"
			],
			"BaseMDEF": 30,
			"BaseMDEF2": 190,
			"BaseSKILLDMG": 14,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"16": {
			"identifiedDisplayName": "Iron Gauntlets",
			"identifiedResourceName": "\xb9\xce\xc3\xb8\xc0\xc7\xb1\xdb\xb7\xaf\xba\xea",
			"identifiedDescriptionName": [
				"Gloves $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$bonus1$% CRIT"
			],
			"BaseHP": 17,
			"BaseDEF": 8,
			"BaseBonus1": 16,
			"Multiplier1": 2,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
			"17": {
			"identifiedDisplayName": "Steel Gauntlets",
			"identifiedResourceName": "\xb8\xed\xbb\xe7\xbc\xf6\xc0\xc7\xc0\xe5\xb0\xa9",
			"identifiedDescriptionName": [
				"Gloves $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$bonus1$% CRIT"
			],
			"BaseHP": 20,
			"BaseDEF": 9,
			"BaseBonus1": 18,
			"Multiplier1": 2,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
			"18": {
			"identifiedDisplayName": "Soldier Gauntlets",
			"identifiedResourceName": "\xbc\xf6\xb6\xf3\xc0\xc7\xc0\xe5\xb0\xa9",
			"identifiedDescriptionName": [
				"Gloves $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$bonus1$% CRIT"
			],
			"BaseHP": 23,
			"BaseDEF": 10,
			"BaseBonus1": 20,
			"Multiplier1": 2,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"19": {
			"identifiedDisplayName": "Woven Gloves",
			"identifiedResourceName": "\xb1\xdb\xb7\xaf\xba\xea",
			"identifiedDescriptionName": [
				"Gloves $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$aspd$% ASPD",
				"+$cspd$% Casting Speed"
			],
			"BaseHP": 14,
			"BaseASPD": 13,
			"BaseCSPD": 15,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
			"20": {
			"identifiedDisplayName": "Leather Gloves",
			"identifiedResourceName": "\xbb\xe7\xbc\xad\xc0\xc7\xc0\xe5\xb0\xa9",
			"identifiedDescriptionName": [
				"Gloves $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$aspd$% ASPD",
				"+$cspd$% Casting Speed"
			],
			"BaseHP": 16,
			"BaseASPD": 14,
			"BaseCSPD": 17,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
			"21": {
			"identifiedDisplayName": "Regal Gloves",
			"identifiedResourceName": "\xbf\xc0\xb8\xa6\xb7\xb9\xbe\xd3\xc0\xc7\xc0\xe5\xb0\xa9",
			"identifiedDescriptionName": [
				"Gloves $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$aspd$% ASPD",
				"+$cspd$% Casting Speed"
			],
			"BaseHP": 18,
			"BaseASPD": 15,
			"BaseCSPD": 19,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"22": {
			"identifiedDisplayName": "Reinforced Belt",
			"identifiedResourceName": "\xbd\xc3\xb3\xeb\xba\xf1\xc0\xc7\xc7\xe3\xb8\xae\xb6\xec",
			"identifiedDescriptionName": [
				"Belt $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$ Base HP"
			],
			"BaseBonus1": 20,
			"Multiplier1": 5,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"23": {
			"identifiedDisplayName": "Leather Belt",
			"identifiedResourceName": "\xba\xa7\xc6\xae",
			"identifiedDescriptionName": [
				"Belt $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$bonus1$% DEF"
			],
			"BaseHP": 15,
			"BaseBonus1": 10,
			"Multiplier1": 2,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"24": {
			"identifiedDisplayName": "Silken Sash",
			"identifiedResourceName": "\xb8\xf1\xba\xb8\xc8\xa3\xb4\xeb",
			"identifiedDescriptionName": [
				"Belt $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$bonus1$% MDEF"
			],
			"BaseHP": 15,
			"BaseBonus1": 15,
			"Multiplier1": 2,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"25": {
			"identifiedDisplayName": "Layered Shawl",
			"identifiedResourceName": "\xb8\xd3\xc7\xc3\xb7\xaf",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$eva$ EVA"
			],
			"BaseHP": 6,
			"BaseEVADE": 40,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
			"26": {
			"identifiedDisplayName": "Wool Scarf",
			"identifiedResourceName": "\xbf\xef\xbd\xba\xc4\xab\xc7\xc1",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$eva$ EVA"
			],
			"BaseHP": 7,
			"BaseEVADE": 45,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
			"27": {
			"identifiedDisplayName": "Feathered Muffler",
			"identifiedResourceName": "\xb8\xc5\xc0\xc7\xb3\xaf\xb0\xb3\xbf\xca",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$eva$ EVA"
			],
			"BaseHP": 8,
			"BaseEVADE": 50,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"28": {
			"identifiedDisplayName": "Iron Spaulders",
			"identifiedResourceName": "\xb0\xd4\xba\xea\xb3\xd7\xc0\xcc\xbe\xee\xb1\xfa\xc0\xe5\xbd\xc4",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$eva$ EVA"
			],
			"BaseHP": 19,
			"BaseDEF": 12,
			"BaseEVADE": 10,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
			"29": {
			"identifiedDisplayName": "Steel Pauldron",
			"identifiedResourceName": "\xc6\xfa\xb5\xe5\xb7\xb1",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$eva$ EVA"
			],
			"BaseHP": 21,
			"BaseDEF": 14,
			"BaseEVADE": 11,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
			"30": {
			"identifiedDisplayName": "Runic Pauldron",
			"identifiedResourceName": "\xbf\xec\xb8\xa3\xc0\xc7\xb8\xc1\xc5\xe4",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$eva$ EVA"
			],
			"BaseHP": 23,
			"BaseDEF": 16,
			"BaseEVADE": 12,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"31": {
			"identifiedDisplayName": "Leather Shoes",
			"identifiedResourceName": "\xbd\xb4\xc1\xee",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$eva$ EVA",
				"+$cel$% to MSPD"
			],
			"BaseEVADE": 24,
			"BaseCEL": 8,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
			"32": {
			"identifiedDisplayName": "Reinforced Shoes",
			"identifiedResourceName": "\xc3\xca\xba\xb8\xc0\xda\xbf\xeb\xbd\xb4\xc1\xee",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$eva$ EVA",
				"+$cel$% to MSPD"
			],
			"BaseEVADE": 27,
			"BaseCEL": 9,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
			"33": {
			"identifiedDisplayName": "Groundpounders",
			"identifiedResourceName": "\xba\xf1\xb4\xd9\xb8\xa3\xc0\xc7\xba\xce\xc3\xf7",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$eva$ EVA",
				"+$cel$% to MSPD"
			],
			"BaseEVADE": 30,
			"BaseCEL": 10,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"34": {
			"identifiedDisplayName": "Plated Boots",
			"identifiedResourceName": "\xc7\xc1\xb8\xae\xc4\xda\xbd\xb4\xc1\xee",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$cel$% to MSPD"
			],
			"BaseHP": 16,
			"BaseDEF": 9,
			"BaseCEL": 6,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
			"35": {
			"identifiedDisplayName": "Ironscale Boots",
			"identifiedResourceName": "\xb0\xd4\xba\xea\xb3\xd7\xc0\xcc\xc0\xc7\xb1\xba\xc8\xad",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$cel$% to MSPD"
			],
			"BaseHP": 18,
			"BaseDEF": 10,
			"BaseCEL": 6,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
			"36": {
			"identifiedDisplayName": "Steel Greaves",
			"identifiedResourceName": "\xb1\xd7\xb8\xae\xba\xea",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$cel$% to MSPD"
			],
			"BaseHP": 20,
			"BaseDEF": 11,
			"BaseCEL": 7,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"37": {
			"identifiedDisplayName": "Prayer Beads",
			"identifiedResourceName": "\xb7\xce\xc0\xda\xb8\xae",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$ MDEF",
			],
			"BaseBonus1": 30,
			"Multiplier1": 6,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"38": {
			"identifiedDisplayName": "Ritual Incense",
			"identifiedResourceName": "\xc7\xc7\xbb\xe7\xc7\xe2\xc6\xf7",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$% Skill Damage",
				"+$bonus2$% Healing Power",
			],
			"BaseBonus1": 8,
			"Multiplier1": 2,
			"BaseBonus2": 10,
			"Multiplier2": 2,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"39": {
			"identifiedDisplayName": "Crystalline Ring",
			"identifiedResourceName": "\xb4\xd9\xc0\xcc\xbe\xc6\xb9\xdd\xc1\xf6",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$ MP",
			],
			"BaseBonus1": 20,
			"Multiplier1": 4,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"40": {
			"identifiedDisplayName": "Diamond Necklace",
			"identifiedResourceName": "\xb3\xd7\xc5\xac\xb8\xae\xbd\xba",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$% MP Regen",
				"+$bonus2$% Casting Speed",
			],
			"BaseBonus1": 20,
			"Multiplier1": 2,
			"BaseBonus2": 14,
			"Multiplier2": 2,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"41": {
			"identifiedDisplayName": "Verdant Runestone",
			"identifiedResourceName": "\xb7\xe9\xbd\xba\xc5\xe6_\xba\xa3\xb8\xa3\xc4\xab\xb3\xaa",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$% HP Regen",
			],
			"BaseBonus1": 30,
			"Multiplier1": 2,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"42": {
			"identifiedDisplayName": "Warding Herbs",
			"identifiedResourceName": "\xb5\xb6\xc3\xca_\xbd\xba\xc4\xda\xc6\xfa\xb8\xae\xbe\xc6",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"-$bonus1$% Status Ailment Duration",
			],
			"BaseBonus1": 10,
			"Multiplier1": 2,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"43": {
			"identifiedDisplayName": "Golden Coin",
			"identifiedResourceName": "\xb0\xf1\xb5\xe5\xc4\xda\xc0\xce",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$ LUK",
			],
			"BaseBonus1": 5,
			"Multiplier1": 10,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"44": {
			"identifiedDisplayName": "Badge of Valor",
			"identifiedResourceName": "\xc0\xfc\xc5\xf5\xc8\xd6\xc0\xe5",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$% Basic Attack Damage",
			],
			"BaseBonus1": 10,
			"Multiplier1": 3,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"45": {
			"identifiedDisplayName": "Silver Armlet",
			"identifiedResourceName": "\xc0\xba\xbc\xbc\xb0\xf8\xc6\xc8\xc2\xee",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus3$% to CRIT",
			],
			"BaseBonus3": 10,
			"Multiplier3": 8,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
			"46": {
			"identifiedDisplayName": "Iron Bangle",
			"identifiedResourceName": "\xbe\xc6\xc0\xcc\xbe\xf0\xb8\xae\xbd\xba\xc6\xae",
			"identifiedDescriptionName": [
				"Accessory $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$% to CRIT DMG",
			],
			"BaseBonus1": 8,
			"Multiplier1": 8,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
		"100": {
			"identifiedDisplayName": "Curved Blade",
			"identifiedResourceName": "\xbd\xc3\xb9\xcc\xc5\xcd",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 9,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 2
		},
		"101": {
			"identifiedDisplayName": "Arming Sword",
			"identifiedResourceName": "\xbd\xba\xc5\xb8\xba\xed\xb7\xb9\xc0\xcc\xb5\xe5",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 10,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 2
		},
		"102": {
			"identifiedDisplayName": "Hallowed Sabre",
			"identifiedResourceName": "\xbc\xbc\xc0\xcc\xb9\xf6",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 11,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 2
		},
		"103": {
			"identifiedDisplayName": "Cudgel",
			"identifiedResourceName": "\xbd\xba\xb8\xc5\xbc\xc5",
			"identifiedDescriptionName": [
				"Mace $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 15,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 8
		},
		"104": {
			"identifiedDisplayName": "Morningstar",
			"identifiedResourceName": "\xb8\xf0\xb4\xd7\xbd\xba\xc5\xb8",
			"identifiedDescriptionName": [
				"Mace $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 16,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 8
		},
		"105": {
			"identifiedDisplayName": "Aklys",
			"identifiedResourceName": "\xc4\xab\xb8\xa3\xb0\xa1\xb8\xde\xc0\xcc\xbd\xba",
			"identifiedDescriptionName": [
				"Mace $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 17,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 8
		},
		"106": {
			"identifiedDisplayName": "Spiritual Dagger",
			"identifiedResourceName": "\xbe\xc6\xbd\xb4\xb6\xf3",
			"identifiedDescriptionName": [
				"Athame $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				"+$cspd$% Casting Speed",
			],
			"BaseMAG": 8,
			"BaseCSPD": 20,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 1
		},
		"107": {
			"identifiedDisplayName": "Ceremonial Dagger",
			"identifiedResourceName": "\xbf\xa1\xc0\xce\xbc\xc7\xc6\xae\xb4\xeb\xb0\xc5",
			"identifiedDescriptionName": [
				"Athame $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				"+$cspd$% Casting Speed",
			],
			"BaseMAG": 9,
			"BaseCSPD": 24,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 1
		},
		"108": {
			"identifiedDisplayName": "Ivory Dagger",
			"identifiedResourceName": "\xc7\xcf\xc4\xed\xc1\xf8",
			"identifiedDescriptionName": [
				"Athame $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				"+$cspd$% Casting Speed",
			],
			"BaseMAG": 10,
			"BaseCSPD": 28,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 1
		},
		"109": {
			"identifiedDisplayName": "Longsword",
			"identifiedResourceName": "\xb9\xd9\xbd\xba\xc5\xb8\xb5\xe5\xbc\xd2\xb5\xe5",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Cleaves with Basic Attacks."
			],
			"BaseATK": 12,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 3
		},
		"110": {
			"identifiedDisplayName": "Claymore",
			"identifiedResourceName": "\xc5\xa9\xb7\xb9\xc0\xcc\xb8\xf0\xbe\xee",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Cleaves with Basic Attacks."
			],
			"BaseATK": 13,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 3
		},
		"111": {
			"identifiedDisplayName": "Zweihander",
			"identifiedResourceName": "\xc1\xee\xb9\xd9\xc0\xcc\xc7\xda\xb4\xf5",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Cleaves with Basic Attacks."
			],
			"BaseATK": 14,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 3
		},
		"112": {
			"identifiedDisplayName": "Broadaxe",
			"identifiedResourceName": "\xb9\xe8\xc6\xb2\xbe\xd7\xbd\xba",
			"identifiedDescriptionName": [
				"Axe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 21,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 7
		},
		"113": {
			"identifiedDisplayName": "Battleaxe",
			"identifiedResourceName": "\xbf\xc0\xc5\xb0\xbd\xac\xbe\xd7\xbd\xba",
			"identifiedDescriptionName": [
				"Axe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 23,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 7
		},
		"114": {
			"identifiedDisplayName": "Grand Labrys",
			"identifiedResourceName": "\xb1\xd7\xb7\xb9\xc0\xcc\xc6\xae\xbe\xd7\xbd\xba",
			"identifiedDescriptionName": [
				"Axe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 25,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 7
		},
		"115": {
			"identifiedDisplayName": "Cedar Bow",
			"identifiedResourceName": "\xba\xb8\xbf\xec",
			"identifiedDescriptionName": [
				"Bow $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 13,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 11
		},
		"116": {
			"identifiedDisplayName": "Composite Bow",
			"identifiedResourceName": "\xb5\xb5\xb5\xcf\xc0\xc7\xc8\xb0",
			"identifiedDescriptionName": [
				"Bow $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 14,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 11
		},
		"117": {
			"identifiedDisplayName": "Hunting Bow",
			"identifiedResourceName": "\xc7\xe5\xc5\xcd\xba\xb8\xbf\xec",
			"identifiedDescriptionName": [
				"Bow $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
			],
			"BaseATK": 15,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 11
		},
		"118": {
			"identifiedDisplayName": "Oak Staff",
			"identifiedResourceName":  "\xb7\xd4\xb5\xe5",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
			],
			"BaseMAG": 24,
			"Rating": 1,
			"slotCount": 0,
			"ClassNum": 10
		},
		"119": {
			"identifiedDisplayName": "Arcane Wand",
			"identifiedResourceName": "\xbe\xc6\xc5\xa9\xbf\xcf\xb5\xe5",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
			],
			"BaseMAG": 27,
			"Rating": 2,
			"slotCount": 0,
			"ClassNum": 10
		},
		"120": {
			"identifiedDisplayName": "Ruby Rod",
			"identifiedResourceName": "\xc4\xa1\xc0\xaf\xc0\xc7\xc1\xf6\xc6\xce\xc0\xcc",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
			],
			"BaseMAG": 30,
			"Rating": 3,
			"slotCount": 0,
			"ClassNum": 10
		},
		"52000": {
			"identifiedDisplayName": "Niflheim's Grasp",
			"identifiedResourceName": "\xb3\xaa\xba\xea\xc0\xc7\xc5\xac\xb7\xce\xbd\xba",
			"identifiedDescriptionName": [
				"Light Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$mdef$ MDEF",
				" ",
				"Attackers feel the cold grip of\nNiflheim.",
			],
			"BaseHP": 26,
			"BaseMP": 17,
			"BaseDEF": 12,
			"BaseMDEF": 66,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52001": {
			"identifiedDisplayName": "Cleric's Robe",
			"identifiedResourceName": "\xc0\xba\xc7\xfd\xc0\xc7\xbc\xba\xc0\xc7",
			"identifiedDescriptionName": [
				"Light Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$mdef$ MDEF",
				"+$bonus1$% Healing Power",
				" ",
				"Grants [Tend Wounds].",
			],
			"BaseHP": 20,
			"BaseMP": 25,
			"BaseDEF": 13,
			"BaseMDEF": 40,
			"BaseBonus1": 20,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52002": {
			"identifiedDisplayName": "Seraph's Grace",
			"identifiedResourceName": "\xc7\xc1\xb7\xb9\xc0\xcc\xbe\xdf\xc0\xc7\xbf\xdc\xc5\xf5",
			"identifiedDescriptionName": [
				"Light Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$mdef$ MDEF",
				"+100% HP Regen",
			],
			"BaseHP": 40,
			"BaseMP": 15,
			"BaseDEF": 15,
			"BaseMDEF": 35,	
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52003": {
			"identifiedDisplayName": "Blood Oath",
			"identifiedResourceName": "\xb5\xf0\xbe\xc6\xba\xbc\xb7\xe7\xbd\xba\xb7\xce\xba\xea",
			"identifiedDescriptionName": [
				"Light Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$mdef$ MDEF",
				"+$bonus1$% HP restored on Kill",
				"+$bonus2$ MP restored on Kill",
				" ",
				"You no longer naturally\nregenerate HP or MP.",
			],
			"BaseHP": 34,
			"BaseMP": 27,
			"BaseDEF": 20,
			"BaseMDEF": 60,
			"BaseBonus1": 10,
			"Multiplier1": 2,	
			"BaseBonus2": 20,
			"Multiplier2": 2,		
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52004": {
			"identifiedDisplayName": "Assassin's Cloak",
			"identifiedResourceName": "\xbb\xe7\xb6\xf3\xc0\xc7\xc0\xfc\xc5\xf5\xb7\xce\xba\xea",
			"identifiedDescriptionName": [
				"Mage Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$bonus1$ Skill CRIT",
			],
			"BaseHP": 40,
			"BaseMP": 10,
			"BaseDEF": 15,
			"BaseBonus1": 8,
			"Multiplier1": 2,			
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52005": {
			"identifiedDisplayName": "Shifting Sands",
			"identifiedResourceName": "\xc4\xad\xb5\xce\xb6\xf3",
			"identifiedDescriptionName": [
				"Mage Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				"+$cel$% to MSPD",
			],
			"BaseHP": 39,
			"BaseMP": 14,
			"BaseDEF": 27,
			"BaseCEL": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52006": {
			"identifiedDisplayName": "Mach Mail",
			"identifiedResourceName": "\xbf\xeb\xbb\xe7\xc0\xc7\xc6\xae\xb7\xb9\xc0\xcc\xb5\xe5\xb8\xde\xc0\xcf",
			"identifiedDescriptionName": [
				"Mage Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				" ",
				"You gain bonus attack\nspeed based on your\ncelerity."
			],
			"BaseHP": 41,
			"BaseMP": 5,
			"BaseDEF": 24,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0,
		},
		"52007": {
			"identifiedDisplayName": "Mage Ward",
			"identifiedResourceName": "\xc4\xa5\xc8\xe6\xc0\xc7\xb0\xa9\xbf\xca",
			"identifiedDescriptionName": [
				"Mage Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mp$ MP",
				"+$def$ DEF",
				" ",
				"Enemies who target you with\nskills are Silenced.",
			],
			"BaseHP": 43,
			"BaseMP": 12,
			"BaseDEF": 30,		
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0,
		},
		"52008": {
			"identifiedDisplayName": "Golden Plate",
			"identifiedResourceName": "\xb0\xad\xc8\xad\xb8\xde\xc0\xcf",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+35 LUK",
			],
			"BaseHP": 50,
			"BaseDEF": 30,		
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52009": {
			"identifiedDisplayName": "Serpentine Mail",
			"identifiedResourceName": "\xb3\xaa\xb0\xa1\xc0\xc7\xba\xf1\xb4\xc3\xb0\xa9\xbf\xca",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				" ",
				"Return $bonus1$% of physical\ndamage taken back to the\nattacker.",
			],
			"BaseHP": 127,	
			"BaseBonus1": 50,
			"Multiplier1": 5,		
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52010": {
			"identifiedDisplayName": "Hardrock Barrier",
			"identifiedResourceName": "\xb0\xd4\xba\xea\xb3\xd7\xc0\xcc\xc0\xc7\xb0\xa9\xbf\xca",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
			],
			"BaseHP": 15,
			"BaseDEF": 87,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52011": {
			"identifiedDisplayName": "Adamantite Armor",
			"identifiedResourceName": "\xb8\xde\xc5\xd7\xbf\xc0\xc7\xc3\xb7\xb9\xc0\xcc\xc6\xae",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				" ",
				"+$bonus1$% Physical Damage Resistance",
				"+$bonus2$% Magical Damage Vulnerability",
			],
			"BaseHP": 80,
			"BaseBonus1": 15,
			"Multiplier1": 2,
			"BaseBonus2": 15,
			"Multiplier2": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52012": {
			"identifiedDisplayName": "Soul of the Earth",
			"identifiedResourceName": "\xb6\xf3\xc0\xcc\xc7\xc1\xb8\xb5\xc5\xa9",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				" ",
				"You regenerate 5% of your\nMax HP per second, even\nwhile moving.",
			],
			"BaseHP": 98,
			"BaseDEF": 30,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52013": {
			"identifiedDisplayName": "Betrayer's Plate",
			"identifiedResourceName": "\xb5\xf0\xbe\xc6\xba\xbc\xb7\xe7\xbd\xba\xbe\xc6\xb8\xd3",
			"identifiedDescriptionName": [
				"Heavy Armor $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				" ",
				"Some defeated enemies will join your side.",
			],
			"BaseHP": 53,
			"BaseDEF": 47,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52014": {
			"identifiedDisplayName": "Golden Buckler",
			"identifiedResourceName": "\xb0\xad\xc8\xad\xb9\xf6\xc5\xac\xb7\xaf",
			"identifiedDescriptionName": [
				"Shield $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def2$% Physical Block",
				"+$mdef2$% Magical Block",
				"+35 LUK",
			],
			"BaseHP": 20,
			"BaseDEF2": 8,
			"BaseMDEF2": 8,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1
		},
		"52015": {
			"identifiedDisplayName": "Derelict Tome",
			"identifiedResourceName": "\xc7\xf6\xc0\xda\xc0\xc7\xc0\xcf\xb1\xe2",
			"identifiedDescriptionName": [
				"Off-Hand $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
			],
			"BaseMAG": 10,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52016": {
			"identifiedDisplayName": "Lodestone Shield",
			"identifiedResourceName": "\xb7\xce\xbb\xe7\xbd\xaf\xb5\xe5",
			"identifiedDescriptionName": [
				"Shield $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def2$% Physical Block",
				" ",
				"Grants [Lodestone Burst].",
			],
			"BaseHP": 25,
			"BaseDEF2": 18,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1
		},
		"52017": {
			"identifiedDisplayName": "Null Field",
			"identifiedResourceName": "\xc0\xcc\xb9\xc3\xb5\xe5\xbd\xaf\xb5\xe5",
			"identifiedDescriptionName": [
				"Shield $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$mdef2$% Magical Block",
				" ",
				"You cannot evade physical attacks.",
			],
			"BaseHP": 125,	
			"BaseMDEF2": 32,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1
		},
		"52018": {
			"identifiedDisplayName": "King's Guard",
			"identifiedResourceName": "\xc0\xd3\xc6\xe4\xb8\xae\xbe\xf3\xb0\xa1\xb5\xe5",
			"identifiedDescriptionName": [
				"Shield $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def2$% Physical Block",
				"+$mdef2$% Magical Block",
				" ",
				"Heal $bonus1$% of the damage an\nevaded attack would have\ndealt.",
			],
			"BaseHP": 25,
			"BaseDEF2": 10,
			"BaseMDEF2": 10,
			"BaseBonus1": 15,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1
		},
		"52019": {
			"identifiedDisplayName": "Main Gauche",
			"identifiedResourceName": "\xc4\xda\xbf\xf6\xb5\xe5",
			"identifiedDescriptionName": [
				"Off-Hand $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def2$% Physical Block",
			],
			"BaseDEF2": 21,	
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52020": {
			"identifiedDisplayName": "Backsword",
			"identifiedResourceName": "\xbf\xac\xb0\xcb",
			"identifiedDescriptionName": [
				"Off-Hand $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$bonus1$% ATK",
			],
			"BaseBonus1": 5,
			"Multiplier1": 4,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52021": {
			"identifiedDisplayName": "Immaterial Manteau",
			"identifiedResourceName": "\xbd\xba\xc5\xb2\xbf\xc0\xba\xea\xba\xa5\xc5\xf5\xbd\xba",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def$ DEF",
				"+$eva$ EVA",
				" ",
				"You have an additional\nchance to evade any attack\nor spell while at low life.",
			],
			"BaseDEF": 6,
			"BaseEVADE": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52022": {
			"identifiedDisplayName": "Golden Shawl",
			"identifiedResourceName": "\xb0\xad\xc8\xad\xb8\xd3\xc7\xc3\xb7\xaf",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def$ DEF",
				"+$eva$ EVA",
				"+35 LUK",
			],
			"BaseDEF": 6,
			"BaseEVADE": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52023": {
			"identifiedDisplayName": "Prismatic Cloak",
			"identifiedResourceName": "\xbf\xa1\xb1\xe6\xb8\xc1\xc5\xe4",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def$ DEF",
				"+$eva$ EVA",
				" ",
				"Attacking enemies are Blinded.",
			],
			"BaseDEF": 7,
			"BaseEVADE": 8,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52024": {
			"identifiedDisplayName": "Midnight Mantle",
			"identifiedResourceName": "\xbf\xbe\xbf\xb5\xc1\xd6\xc0\xc7\xb8\xc1\xc5\xe4",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def$ DEF",
				"+$eva$ EVA",
				"+$bonus1$% Lifesteal",
			],
			"BaseDEF": 3,
			"BaseEVADE": 6,
			"BaseBonus1": 10,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52025": {
			"identifiedDisplayName": "Path of Bravery",
			"identifiedResourceName": "\xb9\xdf\xc5\xb0\xb8\xae\xc0\xc7\xb8\xc1\xc5\xe4",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def$ DEF",
				"+$eva$ EVA",
				" ",
				"Gain 3 EVA for every enemy\ntargeting you.",
			],
			"BaseDEF": 24,
			"BaseEVADE": 3,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52026": {
			"identifiedDisplayName": "Feline's Guile",
			"identifiedResourceName": "\xbe\xdf\xbc\xba\xc0\xc7\xb2\xbf\xb8\xae",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$eva$ EVA",
				"+$cel$% to MSPD",
			],
			"BaseEVADE": 12,
			"BaseCEL": 4,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52027": {
			"identifiedDisplayName": "Assassin's Scarf",
			"identifiedResourceName": "\xb7\xce\xc5\xb0\xc0\xc7\xb8\xd3\xc7\xc3\xb7\xaf",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def$ DEF",
				"+$eva$ EVA",
				" ",
				"Your attacks can mark a\ntarget for death.\n\nMarked targets recieve 25%\nmore damage.", 
			],
			"BaseDEF": 5,
			"BaseEVADE": 6,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52028": {
			"identifiedDisplayName": "Tyrant's Cape",
			"identifiedResourceName": "\xc6\xe7\xb7\xcf\xc0\xc7\xb8\xc1\xc5\xe4",
			"identifiedDescriptionName": [
				"Robe $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def$ DEF",
				"+$eva$ EVA",
				" ",
				"Grants [Dominate].",
			],
			"BaseDEF": 15,
			"BaseEVADE": 4,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52029": {
			"identifiedDisplayName": "Feline's Grace",
			"identifiedResourceName": "\xbe\xdf\xbc\xba\xc0\xc7\xba\xce\xc3\xf7",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$cel$% to MSPD",
			],
			"BaseCEL": 13,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52030": {
			"identifiedDisplayName": "Golden Boots",
			"identifiedResourceName": "\xb0\xad\xc8\xad\xba\xce\xc3\xf7",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$cel$% to MSPD",
				"+35 LUK",
			],
			"BaseHP": 10,
			"BaseDEF": 5,
			"BaseCEL": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52031": {
			"identifiedDisplayName": "Mystwalkers",
			"identifiedResourceName": "\xbd\xa6\xb5\xb5\xbf\xec\xbf\xf6\xc5\xa9",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$cel$% to MSPD",
				" ",
				"Grants [Shadowstep].",
			],
			"BaseHP": 8,
			"BaseDEF": 6,
			"BaseCEL": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52032": {
			"identifiedDisplayName": "Bunny Slippers",
			"identifiedResourceName": "\xbd\xbd\xb8\xae\xc6\xdb",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$cel$% to MSPD",
				" ",
				"Grants [Rest].",
				" ",
				"Your Sleep is much more\nrestful.",
			],
			"BaseHP": 10,
			"BaseDEF": 1,
			"BaseCEL": 8,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52033": {
			"identifiedDisplayName": "Leg Augmentation",
			"identifiedResourceName": "\xb9\xce\xc3\xb8\xbc\xba\xba\xb8\xbf\xcf\xc0\xe5\xc4\xa1",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$def$ DEF",
				" ",
				"Grants [Booster].",
			],
			"BaseDEF": 24,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"52034": {
			"identifiedDisplayName": "Nomad's Passage",
			"identifiedResourceName": "\xbb\xfd\xb8\xed\xb3\xaa\xb9\xab\xc1\xd9\xb1\xe2\xbd\xb4\xc1\xee",
			"identifiedDescriptionName": [
				"Shoes $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$hp$ HP",
				"+$def$ DEF",
				"+$cel$% to MSPD",
				" ",
				"You rapidly regenerate HP\nwhile moving.",
			],
			"BaseHP": 12,
			"BaseDEF": 8,
			"BaseCEL": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"53000": {
			"identifiedDisplayName": "Penguin Feather",
			"identifiedResourceName": "\xb5\xbf\xb1\xd7\xb6\xf5\xb1\xea\xc5\xd0",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"Grants [Call Penguin], the ability to summon a Penguin to your side.",
				" ",
				"During battle your summoned Penguin will toss you refreshing drinks, healing 10% HP and 20 SP instantly as well as putting one in your inventory to drink later.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Grants [Call Penguin]."]
		},
		"53001": {
			"identifiedDisplayName": "James",
			"identifiedResourceName": "\xb4\xfa\xb1\xd7\xb7\xb0\xb0\xc5\xb8\xae\xb4\xc2\xc7\xd8\xb0\xf1",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"The cursed skull of James, the undying.",
				" ",
				"Every now and then James will whisper a dark secret to you, giving you a massive boost to a random stat.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Periodic stat boosts."]
		},
		"53002": {
			"identifiedDisplayName": "Mana Battery",
			"identifiedResourceName": "\xba\xa3\xbd\xba\xc6\xdb\xc4\xda\xbe\xee",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"Slowly leeches and stores up to 200 MP from you while active, which can be instantly regained later.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Grants [Mana Charge]."]
		},
		"53003": {
			"identifiedDisplayName": "Temporal Orb",
			"identifiedResourceName": "\xb0\xf1\xb5\xe7\xb7\xce\xb5\xe5\xbf\xc0\xba\xea",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"Your skills will sometimes not trigger their cooldowns when used.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Chance to skip cooldowns."]
		},
		"53004": {
			"identifiedDisplayName": "Mirror of Ages",
			"identifiedResourceName": "\xc8\xad\xb7\xc1\xc7\xd1\xb0\xc5\xbf\xef",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"When hit by a spell, you will sometimes counterattack with the same spell.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Mirror spells by chance."]
		},
		"53005": {
			"identifiedDisplayName": "Fractal Shard",
			"identifiedResourceName": "\xbc\xf6\xc1\xa4\xc1\xb6\xb0\xa2",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"While attacking, you have a chance to create a mirror image of yourself.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Clone yourself when attacking."]
		},
		"53006": {
			"identifiedDisplayName": "Resolute Armband",
			"identifiedResourceName": "\xb8\xed\xb1\xc3\xc0\xc7\xbd\xba\xc4\xab\xc7\xc1",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"Lethal hits won't always kill you.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Lethal hits won't always kill you."]
		},
		"53007": {
			"identifiedDisplayName": "Bonecrusher",
			"identifiedResourceName": "\xbe\xcf\xbb\xec\xc0\xda\xc0\xc7\xbc\xf6\xb0\xa9",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"While unarmed, you gain +300% increased Base ATK.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Quadrupled unarmed BATK."]
		},
		"53008": {
			"identifiedDisplayName": "Seraph's Mercy",
			"identifiedResourceName": "\xbe\xd8\xc1\xa9\xb8\xaf\xb8\xb5",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"When revived, you will come back with full HP and MP.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","Revive at full strength."]
		},
		"53009": {
			"identifiedDisplayName": "Bag of Holding",
			"identifiedResourceName": "\xc6\xf2\xb9\xfc\xc7\xd1\xc1\xd6\xb8\xd3\xb4\xcf",
			"identifiedDescriptionName": [
				"Accessory",
				"Unique Equipped",
				" ",
				"Your weight capacity is increased by 200.",
			],
			"slotCount": 0,
			"ClassNum": 0,
			"condensedDesc": ["Accessory"," ","+200 Weight Capacity"]
		},
		"54000": {
			"identifiedDisplayName": "Hydrangea Sword",
			"identifiedResourceName": "\x68\x79\x64\x72\x61\x6E\x67\x65\x61",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$crit$ CRIT",
				"+$bonus1$% Physical Skill Damage", 
			],
			"BaseATK": 10,
			"BaseCRIT": 10,
			"BaseBonus1": 15,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 3,
			"flavortext": "Eternal determination."
		},
		"54001": {
			"identifiedDisplayName": "Last Breath",
			"identifiedResourceName": "\xbe\xee\xbb\xf5\xbd\xc5\xb4\xeb\xb0\xc5",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$bonus1$% CRIT DMG",
				" ",
				"Your skills cannot critically hit." 
			],
			"BaseATK": 11,
			"BaseBonus1": 50,
			"Multiplier1": 3,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54002": {
			"identifiedDisplayName": "Soulstealer",
			"identifiedResourceName": "\xc8\xab\xb7\xc3\xc0\xc7\xb0\xcb",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$bonus1$% Manasteal",
			],
			"BaseATK": 2,
			"BaseBonus1": 5,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54003": {
			"identifiedDisplayName": "Lamentation",
			"identifiedResourceName": "\xc5\xd7\xc0\xcf\xc7\xce",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"You deal $bonus1$% more physical\ndamage while attacking from\nbehind.",
			],
			"BaseATK": 7,
			"BaseBonus1": 60,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54004": {
			"identifiedDisplayName": "Firebrand",
			"identifiedResourceName": "\xc5\xc2\xbe\xe7\xb0\xcb",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Your critical hits Ignite enemies.",
			],
			"BaseATK": 9,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54005": {
			"identifiedDisplayName": "Tetra Vortex",
			"identifiedResourceName": "\xbf\xa4\xb7\xb9\xb8\xe0\xc5\xbb\xbc\xd2\xb5\xe5",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"You will unleash elemental fury\nwhile attacking.",
			],
			"BaseATK": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54006": {
			"identifiedDisplayName": "Godslayer",
			"identifiedResourceName": "\xbf\xa2\xbd\xba\xc4\xae\xb8\xae\xb9\xf6",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"You deal $bonus1$% more physical\ndamage to Boss Monsters.",
			],
			"BaseATK": 6,
			"BaseBonus1": 40,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54007": {
			"identifiedDisplayName": "Estoc",
			"identifiedResourceName": "\xbd\xb4\xb9\xd9\xc0\xcc\xc3\xbc\xb8\xa3\xbb\xfe\xba\xa7",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$bonus1$% CRIT DMG",
			],
			"BaseATK": 2,
			"BaseBonus1": 20,
			"Multiplier1": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54008": {
			"identifiedDisplayName": "Icebrand",
			"identifiedResourceName": "\xbe\xc6\xc0\xcc\xbd\xba\xc6\xc8\xbd\xc3\xbf\xc2",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"20% Chance to Freeze on Hit",
				" ",
				"Your attacks against frozen\nenemies will always critically hit.",
			],
			"BaseATK": 9,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54009": {
			"identifiedDisplayName": "Hardedge",
			"identifiedResourceName": "\xbf\xc0\xc5\xb0\xbd\xac\xbc\xd2\xb5\xe5",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"You attacks cannot critically hit.",
			],
			"BaseATK": 16,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54010": {
			"identifiedDisplayName": "Dueling Sword",
			"identifiedResourceName": "\xb7\xe7\xba\xa3\xb8\xa3",
			"identifiedDescriptionName": [
				"Shortsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"You deal $bonus1$% more physical\ndamage while dueling a\nmonster.",
			],
			"BaseATK": 9,
			"BaseBonus1": 25,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 1,
		},
		"54011": {
			"identifiedDisplayName": "Sanguine Sword",
			"identifiedResourceName": "\xba\xed\xb7\xaf\xb5\xf0\xc0\xcc\xc5\xcd",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"$bonus1$% Chance to Bleed on Hit",
				" ",
				"Restore 5% of your HP when\nkilling a monster.",
			],
			"BaseATK": 11,
			"BaseBonus1": 10,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 3,
		},
		"54012": {
			"identifiedDisplayName": "Durandal",
			"identifiedResourceName": "\xbe\xcb\xc4\xab\xba\xea\xb8\xb5\xb0\xc5",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$bonus1$% ASPD",
				"+25% MP Consumption",
			],
			"BaseATK": 15,
			"BaseBonus1": 10,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 3,
		},
		"54013": {
			"identifiedDisplayName": "Atlas",
			"identifiedResourceName": "\xbe\xc6\xc6\xae\xb7\xce\xbd\xba\xc0\xc7\xc8\xe4\xb1\xe2",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"-30% ASPD",
				"+1 Weapon Range",
				" ",
				"This weapon has a large swing.",
			],
			"BaseATK": 16,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 3,
		},
		"54014": {
			"identifiedDisplayName": "Honor of the Pure",
			"identifiedResourceName": "\xc4\xab\xc3\xf7\xb9\xdf\xb0\xd4\xb8\xa3",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$bonus1$% HP",
				" ",
				"You are immune to Poison,\nStun, Bleed, Blind, and Silence.",
			],
			"BaseATK": 10,
			"BaseBonus1": 5,
			"Multiplier1": 3,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 3,
		},
		"54015": {
			"identifiedDisplayName": "Adamantite Blade",
			"identifiedResourceName": "\xc5\xa9\xb7\xd2\xb8\xde\xc5\xbb\xc5\xf5\xc7\xda\xb5\xe5\xbc\xd2\xb5\xe5",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$bonus1$% Physical Damage Resistance",
				"+$bonus2$% Magical Damage Vulnerability",
			],
			"BaseATK": 10,
			"BaseBonus1": 15,
			"Multiplier1": 2,
			"BaseBonus2": 15,
			"Multiplier2": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 3,
		},
		"54016": {
			"identifiedDisplayName": "Phantasm",
			"identifiedResourceName": "\xc1\xd7\xc0\xbd\xc0\xc7\xc0\xce\xb5\xb5\xc0\xda",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Your attacks will always\nDouble Strike.",
			],
			"BaseATK": 5,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 3,
		},
		"54017": {
			"identifiedDisplayName": "Dragon's Ire",
			"identifiedResourceName": "\xb5\xe5\xb7\xa1\xb0\xef\xbd\xbd\xb7\xb9\xc0\xcc\xbe\xee",
			"identifiedDescriptionName": [
				"Knightsword $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"You can assume a\nDragonform while attacking,\ndoubling your Base ATK.",
			],
			"BaseATK": 8,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 3,
		},
		"54018": {
			"identifiedDisplayName": "Guillotine",
			"identifiedResourceName": "\xb1\xe6\xb7\xce\xc6\xbe",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Execute low HP targets.",
			],
			"BaseATK": 14,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54019": {
			"identifiedDisplayName": "Bardiche",
			"identifiedResourceName": "\xb9\xf6\xb5\xf0\xbd\xb4",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+2 Weapon Range",
			],
			"BaseATK": 15,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54020": {
			"identifiedDisplayName": "Behemoth Sledge",
			"identifiedResourceName": "\xba\xea\xb6\xf3\xb5\xf0\xbf\xf2\xb5\xb9\xb8\xc1\xc4\xa1",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"-20% ASPD",
				"+$bonus1$% Lifesteal",
			],
			"BaseATK": 18,
			"BaseBonus1": 10,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54021": {
			"identifiedDisplayName": "Heartbreaker",
			"identifiedResourceName": "\xb1\xd7\xb7\xb9\xc0\xcc\xc6\xae\xbe\xd7\xbd\xba",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Your attacks will ignore your\ntarget's DEF.",
			],
			"BaseATK": 14,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54022": {
			"identifiedDisplayName": "Mythril Axe",
			"identifiedResourceName": "\xba\xa3\xc5\xd7\xb6\xfb\xbe\xd7\xbd\xba",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$bonus1$% CRIT DMG",
				"+10% Chance to Stun on hit",
			],
			"BaseATK": 13,
			"BaseBonus1": 20,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54023": {
			"identifiedDisplayName": "Gravedigger",
			"identifiedResourceName": "\xc7\xd8\xb0\xf1\xc1\xf6\xc6\xce\xc0\xcc",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Your attacks can send\nenemies to a premature\ngrave.",
			],
			"BaseATK": 10,
			"BaseBonus1": 5,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54024": {
			"identifiedDisplayName": "Strongarm Hammer",
			"identifiedResourceName": "\xba\xa3\xc5\xd7\xb6\xfb\xc7\xdc\xb8\xd3",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$bonus1$% STR",
			],
			"BaseATK": 13,
			"BaseBonus1": 20,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54025": {
			"identifiedDisplayName": "Spanner",
			"identifiedResourceName": "\xbd\xba\xc6\xd0\xb3\xca",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Reconstruct slain enemies\nto do your bidding.",
			],
			"BaseATK": 13,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54026": {
			"identifiedDisplayName": "Iron Driver",
			"identifiedResourceName": "\xbe\xc6\xc0\xcc\xbe\xf0\xb5\xe5\xb6\xf3\xc0\xcc\xb9\xf6",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"Your attacks can send an\nenemy flying.",
			],
			"BaseATK": 10,
			"BaseBonus1": 5,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54027": {
			"identifiedDisplayName": "Feline's Ferocity",
			"identifiedResourceName": "\xb0\xed\xbe\xe7\xc0\xcc\xc5\xac\xb7\xb4",
			"identifiedDescriptionName": [
				"Maul $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"Weapon Power: $atk$",
				" ",
				"+$cel$% to MSPD",
				"$bonus1$% Chance to Bleed on Hit",
			],
			"BaseATK": 1,
			"BaseCEL": 3,
			"BaseBonus1": 40,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 8,
		},
		"54028": {
			"identifiedDisplayName": "Lodestone Staff",
			"identifiedResourceName": "\xba\xfb\xc0\xc7\xbc\xf6\xc8\xa3\xc1\xf6\xc6\xce\xc0\xcc",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				" ",
				"You deal $bonus1$% more physical\n damage with basic attacks.",
			],
			"BaseMAG": 8,
			"BaseBonus1": 75,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 10,
		},
		"54029": {
			"identifiedDisplayName": "Jormungandr",
			"identifiedResourceName": "\xbf\xe4\xb8\xa3\xb9\xae\xb0\xa3\xb5\xe5",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				" ",
				"Grants [Call Dragon].",
			],
			"BaseMAG": 10,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 10,
		},
		"54030": {
			"identifiedDisplayName": "From The Beyond",
			"identifiedResourceName": "\xb8\xae\xc4\xa1\xc7\xd8\xb0\xf1\xc1\xf6\xc6\xce\xc0\xcc",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				" ",
				"Your slain enemies won't rest in peace.",
			],
			"BaseMAG": 9,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 10,
		},
		"54031": {
			"identifiedDisplayName": "Crystalline Wand",
			"identifiedResourceName": "\xb8\xb1\xb8\xae\xc1\xee\xbf\xc0\xba\xea\xc0\xa7\xbd\xba",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				" ",
				"Your spells have a high\nchance to Freeze.",
			],
			"BaseMAG": 11,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 10,
		},
		"54032": {
			"identifiedDisplayName": "Tailwind Staff",
			"identifiedResourceName": "\xbd\xba\xc5\xc2\xc7\xc1\xbf\xc0\xba\xea\xc0\xae",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				" ",
				"You gain $bonus1$% to MSPD after hitting\nan enemy with a spell.",
			],
			"BaseMAG": 9,
			"BaseBonus1": 10,
			"Multiplier1": 2,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 10,
		},
		"54033": {
			"identifiedDisplayName": "Dead Man's Cane",
			"identifiedResourceName": "\xb0\xed\xb8\xf1\xb3\xaa\xb9\xab\xc1\xf6\xc6\xce\xc0\xcc",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				" ",
				"You no longer naturally\nregenerate HP.",
			],
			"BaseMAG": 16,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 10,
		},
		"54034": {
			"identifiedDisplayName": "Blightcaster",
			"identifiedResourceName": "\xb8\xde\xc5\xbb\xbd\xba\xc5\xc2\xc7\xc1",
			"identifiedDescriptionName": [
				"Staff $r$",
				"Item Level: $ilvl$",
				"Quality: $quality$%",
				" ",
				"+$mag$ MAG",
				" ",
				"Your spells have a chance to\ncause a random status effect.",
			],
			"BaseMAG": 8,
			"Rating": 4,
			"slotCount": 0,
			"ClassNum": 10,
		},
		"500": {
			"identifiedDisplayName": "Shard of Strength",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ STR",
			],
			"BaseRoll1": 2,
			"RollMultiplier1": 5,
			"slotCount": 0,
			"ClassNum": 0
		},
		"501": {
			"identifiedDisplayName": "Shard of Agility",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ AGI",
			],
			"BaseRoll1": 2,
			"RollMultiplier1": 5,
			"slotCount": 0,
			"ClassNum": 0
		},
		"502": {
			"identifiedDisplayName": "Shard of Vitality",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ VIT",
			],
			"BaseRoll1": 2,
			"RollMultiplier1": 5,
			"slotCount": 0,
			"ClassNum": 0
		},
		"503": {
			"identifiedDisplayName": "Shard of Intelligence",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ INT",
			],
			"BaseRoll1": 2,
			"RollMultiplier1": 5,
			"slotCount": 0,
			"ClassNum": 0
		},
		"504": {
			"identifiedDisplayName": "Shard of Mastery",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ MST",
			],
			"BaseRoll1": 2,
			"RollMultiplier1": 5,
			"slotCount": 0,
			"ClassNum": 0
		},
		"505": {
			"identifiedDisplayName": "Shard of Luck",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ LUK",
			],
			"BaseRoll1": 5,
			"RollMultiplier1": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"506": {
			"identifiedDisplayName": "Shard of Health",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$% HP",
			],
			"BaseRoll1": 4,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"507": {
			"identifiedDisplayName": "Shard of Mana",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ MP",
			],
			"BaseRoll1": 5,
			"RollMultiplier1": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"508": {
			"identifiedDisplayName": "Shard of Defense",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ DEF",
			],
			"BaseRoll1": 3,
			"RollMultiplier1": 7,
			"slotCount": 0,
			"ClassNum": 0
		},
		"509": {
			"identifiedDisplayName": "Shard of Magic Defense",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ MDEF",
			],
			"BaseRoll1": 5,
			"RollMultiplier1": 8,
			"slotCount": 0,
			"ClassNum": 0
		},
		"510": {
			"identifiedDisplayName": "Shard of Critical Chance",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll3$% to CRIT",
			],
			"BaseRoll3": 4,
			"RollMultiplier3": 10,
			"slotCount": 0,
			"ClassNum": 0
		},
		"511": {
			"identifiedDisplayName": "Shard of Critical Damage",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$% to CRIT DMG",
			],
			"BaseRoll1": 5,
			"RollMultiplier1": 5,
			"slotCount": 0,
			"ClassNum": 0
		},
		"512": {
			"identifiedDisplayName": "Shard of Attack Speed",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$% ASPD",
			],
			"BaseRoll1": 5,
			"RollMultiplier1": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"513": {
			"identifiedDisplayName": "Shard of Evasion",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ EVA",
			],
			"BaseRoll1": 8,
			"RollMultiplier1": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"514": {
			"identifiedDisplayName": "Shard of Movespeed",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$% to MSPD",
			],
			"BaseRoll1": 4,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"515": {
			"identifiedDisplayName": "Shard of Health Regen",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$% HP Regen",
			],
			"BaseRoll1": 15,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"516": {
			"identifiedDisplayName": "Shard of Mana Regen",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$% MP Regen",
			],
			"BaseRoll1": 15,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"517": {
			"identifiedDisplayName": "Shard of Lifesteal",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll3$% Lifesteal",
			],
			"BaseRoll3": 8,
			"RollMultiplier3": 10,
			"slotCount": 0,
			"ClassNum": 0
		},
		"518": {
			"identifiedDisplayName": "Shard of Soulsteal",
			"identifiedResourceName": "\xc5\xa9\xb8\xae\xbd\xba\xc5\xbb\xc5\xb0",
			"identifiedDescriptionName": [
				"$shard +$roll1$ MP on Kill",
			],
			"BaseRoll1": 3,
			"RollMultiplier1": 5,
			"slotCount": 0,
			"ClassNum": 0
		},
		"600": {
			"identifiedDisplayName": "Seal of Health",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$% HP",
			],
			"BaseRoll1": 15,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"601": {
			"identifiedDisplayName": "Seal of Mana",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$ MP",
			],
			"BaseRoll1": 30,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"602": {
			"identifiedDisplayName": "Seal of Lethality",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll3$% to CRIT",
				"$seal +$roll2$% to CRIT DMG",
			],
			"BaseRoll3": 25,
			"RollMultiplier3": 3,
			"BaseRoll2": 15,
			"RollMultiplier2": 4,
			"slotCount": 0,
			"ClassNum": 0
		},
		"603": {
			"identifiedDisplayName": "Seal of Aptitude",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal -$roll1$% MP Consumption",
			],
			"BaseRoll1": 10,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"604": {
			"identifiedDisplayName": "Seal of Body",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal -$roll1$% Physical Damage Taken",
			],
			"BaseRoll1": 5,
			"RollMultiplier1": 3,
			"slotCount": 0,
			"ClassNum": 0
		},
		"605": {
			"identifiedDisplayName": "Seal of Mind",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal -$roll1$% Magical Damage Taken",
			],
			"BaseRoll1": 15,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"606": {
			"identifiedDisplayName": "Seal of Fortune",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$ LUK",
				"$seal Gain extra Munny when killing a monster",
			],
			"BaseRoll1": 15,
			"RollMultiplier1": 3,
			"slotCount": 0,
			"ClassNum": 0
		},
		"607": {
			"identifiedDisplayName": "Seal of Broken Will",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$% DEF Penetration",
			],
			"BaseRoll1": 30,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"608": {
			"identifiedDisplayName": "Seal of Broken Spirit",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$% MDEF Penetration",
			],
			"BaseRoll1": 30,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"609": {
			"identifiedDisplayName": "Seal of Paralysis",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$% Chance to Stun with attacks",
				"$seal +$roll2$% Chance to Stun when hit",
			],
			"BaseRoll1": 5,
			"RollMultiplier1": 2,
			"BaseRoll2": 5,
			"RollMultiplier2": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"610": {
			"identifiedDisplayName": "Seal of Venom",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$% Chance to Poison with attacks",
				"$seal +$roll2$% Chance to Poison when hit",
			],
			"BaseRoll1": 10,
			"RollMultiplier1": 2,
			"BaseRoll2": 10,
			"RollMultiplier2": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"611": {
			"identifiedDisplayName": "Seal of Hoarfrost",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$% Chance to Freeze with attacks",
				"$seal +$roll2$% Chance to Freeze when hit",
			],
			"BaseRoll1": 5,
			"RollMultiplier1": 2,
			"BaseRoll2": 5,
			"RollMultiplier2": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"612": {
			"identifiedDisplayName": "Seal of Echoes",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"$seal +$roll1$% Chance to Double Strike",
			],
			"BaseRoll1": 15,
			"RollMultiplier1": 2,
			"slotCount": 0,
			"ClassNum": 0
		},
		"55999": {
			"identifiedDisplayName": "Seal of Faith",
			"identifiedResourceName": "\xb8\xb6\xb7\xc2\xbc\xae_\xb3\xeb\xb6\xfb",
			"identifiedDescriptionName": [
				"+25% Healing Power",
				"+25% Healing Recieved",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"700": {
			"identifiedDisplayName": "Fruit Juice",
			"identifiedResourceName": "\xb5\xa6\xbf\xe4\xb8\xae09",
			"identifiedDescriptionName": [
				"Consumable",
				" ",
				"Heals 10% of your Max HP and 20 MP.",
				"Limit: 5",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"701": {
			"identifiedDisplayName": "Mini Potion",
			"identifiedResourceName": "\xbf\xbb\xb7\xce\xbf\xec\xbd\xbd\xb8\xb2\xc6\xf7\xbc\xc7",
			"identifiedDescriptionName": [
				"Consumable",
				" ",
				"Heals 33% of your Max HP.",
				"Limit: 10",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"702": {
			"identifiedDisplayName": "Stout Potion",
			"identifiedResourceName": "\xb3\xeb\xb6\xf5\xc6\xf7\xbc\xc7",
			"identifiedDescriptionName": [
				"Consumable",
				" ",
				"Heals 66% of your Max HP.",
				"Limit: 10",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"703": {
			"identifiedDisplayName": "Mega Potion",
			"identifiedResourceName": "\xb6\xfb\xc4\xab",
			"identifiedDescriptionName": [
				"Consumable",
				" ",
				"Heals 100% of your Max HP.",
				"Limit: 10",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"704": {
			"identifiedDisplayName": "Salve",
			"identifiedResourceName": "\xb3\xf3\xc3\xe0\xbb\xf8\xb7\xaf\xb8\xb6\xc0\xce\xc1\xf3",
			"identifiedDescriptionName": [
				"Consumable",
				" ",
				"Cures Poison, Silence, and Blind.",
				"Limit: 10",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"705": {
			"identifiedDisplayName": "Goddess Tear",
			"identifiedResourceName": "\xc7\xcf\xb4\xc3\xbb\xf6\xba\xb8\xbc\xae",
			"identifiedDescriptionName": [
				"Consumable",
				" ",
				"Revives a player.",
				"Limit: 5",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"706": {
			"identifiedDisplayName": "Faerie Wing",
			"identifiedResourceName": "\xc4\xbf\xb4\xd9\xb6\xf5\xb3\xaf\xb0\xb3",
			"identifiedDescriptionName": [
				"Consumable",
				" ",
				"Teleport to your Party Leader.",
				"Limit: 5",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"707": {
			"identifiedDisplayName": "Grand Faerie Wing",
			"identifiedResourceName": "\xc8\xad\xb7\xc1\xc7\xd1\xbf\xe4\xc1\xa4\xb3\xaf\xb0\xb3",
			"identifiedDescriptionName": [
				"Consumable",
				"Requires: Party Leader",
				" ",
				"Teleport your party to your side.",
				"Limit: 5",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"800": {
			"identifiedDisplayName": "Mythril Ore",
			"identifiedResourceName": "\xb9\xcc\xbd\xba\xb8\xb1\xb1\xa4\xbc\xae",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"The ore of a highly valuable metal amongst blacksmiths.",
				" ",
				"Can be taken to a Blacksmith to increase the quality of an item by 10%, up to a maximum of 100%.",
			],
			"condensedDesc": ["Crafting Item"," ","+10% Item Quality"],
			"slotCount": 0,
			"ClassNum": 0
		},
		"801": {
			"identifiedDisplayName": "Orichalcum Ore",
			"identifiedResourceName": "\xc0\xba\xb1\xa4\xbc\xae",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"The ore of a highly valuable metal amongst blacksmiths.",
				" ",
				"Can be taken to a Blacksmith to increase the item level of an item by 5, up to a maximum of your current Base Level.",
			],
			"condensedDesc": ["Crafting Item"," ","+5 Item Level"],
			"slotCount": 0,
			"ClassNum": 0
		},
		"802": {
			"identifiedDisplayName": "Empty Bijou",
			"identifiedResourceName": "\x65\x6D\x70\x74\x79\x62\x69\x6A\x6F\x75",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"A jewel prized amongst enchantresses for its affinity for the arcane, although this one is currently devoid of magic energies.",
				" ",
				"Can be taken to an Enchantress to store a shard from an enchanted item for use later, although doing so will destroy the equipment.",
			],
			"condensedDesc": ["Crafting Item"," ","Can hold an enchantment."],
			"slotCount": 0,
			"ClassNum": 0
		},
		"803": {
			"identifiedDisplayName": "Fervent Bijou",
			"identifiedResourceName": "\xbf\xeb\xc0\xc7\xba\xb8\xc1\xd6_\xc8\xb2",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"A jewel prized amongst enchantresses for its affinity for the arcane.",
				" ",
				"Can be taken to an Enchantress to replace a shard in an enchanted item with the shard stored within this one.",
			],
			"condensedDesc": ["Crafting Item"," "],
			"slotCount": 0,
			"ClassNum": 0
		},
		"804": {
			"identifiedDisplayName": "Arcane Bijou",
			"identifiedResourceName": "\xbf\xeb\xc0\xc7\xba\xb8\xc1\xd6_\xc3\xbb",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"A jewel prized amongst enchantresses for its affinity for the arcane.",
				" ",
				"Can be taken to an Enchantress to add a random shard to an item, up to a maximum of three.",
			],
			"condensedDesc": ["Crafting Item"," ","Adds a shard to an item."],
			"slotCount": 0,
			"ClassNum": 0
		},
		"805": {
			"identifiedDisplayName": "Blessed Bijou",
			"identifiedResourceName": "\x62\x6C\x65\x73\x73\x65\x64\x62\x69\x6A\x6F\x75",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"A jewel prized amongst enchantresses for its affinity for the arcane.",
				" ",
				"Can be taken to an Enchantress to replace an item's seal with another one, or to add a seal to an item with three shards.",
			],
			"condensedDesc": ["Crafting Item"," ","Adds a seal to an item."],
			"slotCount": 0,
			"ClassNum": 0
		},
		"806": {
			"identifiedDisplayName": "Capricious Bijou",
			"identifiedResourceName": "\xbf\xeb\xc0\xc7\xba\xb8\xc1\xd6_\xb3\xec",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"A jewel prized amongst enchantresses for its affinity for the arcane.",
				" ",
				"Can be taken to an Enchantress to randomize the current enchantments on an item.",
			],
			"condensedDesc": ["Crafting Item"," ","Rerolls item's enchantments."],
			"slotCount": 0,
			"ClassNum": 0
		},
		"807": {
			"identifiedDisplayName": "Discordant Bijou",
			"identifiedResourceName": "\xbf\xeb\xc0\xc7\xba\xb8\xc1\xd6_\xc8\xab",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"A jewel prized amongst enchantresses for its affinity for the arcane.",
				" ",
				"Can be taken to an Enchantress to completely change the properties of a piece of equipment, giving or taking away any number of enchantments as well as randomizing its quality, sometimes even beyond 100%.",
			],
			"condensedDesc": ["Crafting Item"," ","Completely rerolls an item."],
			"slotCount": 0,
			"ClassNum": 0
		},
		"808": {
			"identifiedDisplayName": "Divine Hammer",
			"identifiedResourceName": "\xc8\xb2\xb1\xdd\xc0\xc7\xb8\xc1\xc4\xa1",
			"identifiedDescriptionName": [
				"Crafting Item",
				" ",
				"A blacksmith's hammer that has been blessed by a Goddess.",
				" ",
				"Can be taken to a Blacksmith to upgrade a normal item of a lower rank to the best of its type, while preserving all of its other aspects.",
			],
			"condensedDesc": ["Crafting Item"," ","Upgrades a normal item."],
			"slotCount": 0,
			"ClassNum": 0
		},
		"809": {
			"identifiedDisplayName": "Coin Bag",
			"identifiedResourceName": "\xc1\xd6\xb8\xd3\xb4\xcf",
			"identifiedDescriptionName": [
				"Consumable",
				" ",
				"Contains a small amount of Munny.\nMay also contain a crafting item.",
			],
			"slotCount": 0,
			"ClassNum": 0
		},
		"19526": {
			"identifiedDisplayName": "Helm",
			"identifiedResourceName": "\xc7\xef\xb8\xa7",
			"identifiedDescriptionName": [
				"Costume - Upper",
				" ",
				"+12% Stability",
			],
			"slotCount": 0,
			"ClassNum": 40
		},
		"20205": {
			"identifiedDisplayName": "Fancy Flower",
			"identifiedResourceName": "\xc0\xe5\xbd\xc4\xbf\xeb\xb2\xc9",
			"identifiedDescriptionName": [
				"Costume - Upper",
				" ",
				"+17% Photosynthesis Efficiency",
			],
			"slotCount": 0,
			"ClassNum": 4
		},
	};
});